# Generated by Django 6.0.4 on 2026-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverypartner_is_deleted_deliverytask_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Returned to Source', 'Returned to Source')], default='Assigned', max_length=30),
        ),
    ]
