# Generated by Django 6.0.4 on 2026-04-29 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='StallCart', max_length=100)),
                ('site_tagline', models.CharField(blank=True, default="India's Premium Fashion Destination", max_length=255)),
                ('logo_primary', models.ImageField(help_text='Primary logo (header/footer). Recommended: PNG with transparent background, max 400px wide.', upload_to='branding/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp'])])),
                ('logo_dark', models.ImageField(blank=True, help_text='Logo for dark backgrounds or dark mode (optional)', null=True, upload_to='branding/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp'])])),
                ('logo_mobile', models.ImageField(blank=True, help_text='Compact/square logo for mobile header (optional)', null=True, upload_to='branding/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp'])])),
                ('favicon', models.ImageField(blank=True, help_text='Browser tab icon. Recommended: 32x32px PNG', null=True, upload_to='branding/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'ico', 'svg'])])),
                ('apple_touch_icon', models.ImageField(blank=True, help_text='iOS home screen icon. Recommended: 180x180px PNG', null=True, upload_to='branding/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])])),
                ('primary_color', models.CharField(default='#2874f0', help_text='Primary hex color (e.g., #2874f0)', max_length=7)),
                ('secondary_color', models.CharField(default='#1a56c4', help_text='Secondary/hover hex color', max_length=7)),
                ('contact_phone', models.CharField(default='+91 8004096954', max_length=20)),
                ('contact_email', models.EmailField(default='stallcart.in@gmail.com', max_length=254)),
                ('contact_whatsapp', models.CharField(blank=True, default='8004096954', max_length=20)),
                ('social_instagram', models.URLField(blank=True, help_text='Full Instagram profile URL')),
                ('social_facebook', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('meta_description', models.TextField(blank=True, default='Shop premium fashion for men & women. Free delivery, easy returns, 100% original products.', max_length=160)),
                ('is_maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode for non-admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
