# Generated by Django 6.0.4 on 2026-05-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_sitesettings_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='social_youtube',
            field=models.URLField(blank=True, help_text='Full YouTube channel URL'),
        ),
    ]
