# Generated by Django 6.0.4 on 2026-05-31 15:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_sitesettings_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Flat delivery charge for orders under threshold (₹)', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('499.00'), help_text='Minimum order amount to qualify for free delivery (₹)', max_digits=10),
        ),
    ]
