# Generated by Django 6.0.4 on 2026-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='daily_otp_limit',
            field=models.IntegerField(default=5, help_text='Maximum OTP requests allowed per recipient in a 24-hour window'),
        ),
    ]
