# Generated by Django 6.0.4 on 2026-06-02 19:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_populate_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='slider_autoplay_seconds',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Autoplay interval for homepage slider in seconds (e.g. 1.0 or 1.5)', max_digits=3),
        ),
    ]
