# Generated by Django 6.0.4 on 2026-06-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_sitesettings_slider_autoplay_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='daily_email_otp_limit',
            field=models.IntegerField(default=5, help_text='Maximum Email OTP requests allowed per recipient in a 24-hour window'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='daily_sms_otp_limit',
            field=models.IntegerField(default=5, help_text='Maximum SMS OTP requests allowed per recipient in a 24-hour window'),
        ),
    ]
