# Generated by Django 6.0.4 on 2026-06-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_sitesettings_daily_email_otp_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_background_jobs',
            field=models.BooleanField(default=True, help_text='Enable or disable background jobs/cron tasks (e.g. Shiprocket tracking, email dispatch)'),
        ),
    ]
