# Generated by Django 6.0.4 on 2026-06-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_sitesettings_enable_background_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='return_policy',
            field=models.TextField(blank=True, default='\n            <h4>1. 7-Day Easy Returns</h4>\n            <p>We want you to love your fashion choices! Items purchased on StallCart are eligible for return <strong>within 7 days of delivery</strong>. To initiate a return, go to your "My Orders" section under your Profile and create a return request.</p>\n\n            <h4>2. Return Conditions</h4>\n            <p>To ensure a successful pickup and refund, please keep the following conditions in mind:</p>\n            <ul>\n              <li><strong>Tags & Labels:</strong> Brand tags, price labels, and barcodes must remain intact and attached to the product.</li>\n              <li><strong>Unused Condition:</strong> Products must be unworn, unwashed, unaltered, and without any stains or odors.</li>\n              <li><strong>Footwear Packaging:</strong> Original brand box is preferred. However, if the box is damaged but the shoes/items themselves are perfect and unused, the return is acceptable.</li>\n              <li><strong>Unboxing Video:</strong> A clear unboxing video is highly recommended for claims on missing or damaged items on delivery.</li>\n            </ul>\n            <p>Our courier agent will perform a quality check at the time of pickup.</p>\n\n            <h4>3. Return Exceptions (Hygiene Products)</h4>\n            <p>For hygiene and health safety reasons, the following categories are strictly non-returnable:</p>\n            <ul>\n              <li>Innerwear, lingerie, swimwear, and socks.</li>\n              <li>Cosmetics and personal care items.</li>\n              <li>Custom-made or personalized clothing.</li>\n            </ul>\n            <p>If you receive a defective or damaged product in these categories, please contact support within 24 hours of delivery.</p>\n\n            <h4>4. Refunds & Replacements</h4>\n            <p>Once the product is successfully picked up and passes quality checks at our warehouse, the refund will be credited back to your original payment source within 5-7 business days.</p>\n        ', null=True, verbose_name='Return Policy'),
        ),
    ]
