# Generated by Django 6.0.4 on 2026-06-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_sitesettings_return_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='otp_expiry_minutes',
            field=models.IntegerField(default=10, help_text='OTP validity duration in minutes'),
        ),
    ]
