# Generated by Django 6.0.4 on 2026-08-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_sitesettings_otp_expiry_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_email_backup',
            field=models.BooleanField(default=True, help_text='Enable or disable daily database backups via email to the administrator'),
        ),
    ]
