# Generated by Django 6.0.4 on 2026-08-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_sitesettings_enable_email_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Enquiry Message')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Is Resolved')),
                ('resolved_notes', models.TextField(blank=True, null=True, verbose_name='Resolution Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Support Enquiry',
                'verbose_name_plural': 'Support Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
