# Generated by Django 6.0.4 on 2026-10-10 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_supportenquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('title', models.CharField(help_text='e.g. Dandiya Mahotsav Lucky Draw 2026', max_length=200)),
                ('slug', models.SlugField(help_text='Unique URL identifier e.g. dandiya-2026', max_length=220, unique=True)),
                ('badge_text', models.CharField(blank=True, default='🔥 Festive Contest', help_text='Badge pill shown on banners', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='Short highlight, e.g. Register & Win 1st, 2nd, 3rd Prizes!', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed rules, terms, and contest info')),
                ('banner_image', models.ImageField(blank=True, help_text='Desktop banner image', null=True, upload_to='campaigns/banners/')),
                ('mobile_banner', models.ImageField(blank=True, help_text='Mobile responsive banner', null=True, upload_to='campaigns/banners/mobile/')),
                ('theme_color', models.CharField(default='#e11d48', help_text='Brand hex color for banners and badges (e.g. #e11d48, #d97706)', max_length=50)),
                ('start_datetime', models.DateTimeField(help_text='Contest start datetime')),
                ('end_datetime', models.DateTimeField(help_text='Contest end datetime')),
                ('target_registrations', models.PositiveIntegerField(default=500, help_text='Target newly created accounts (e.g. 500)')),
                ('status', models.CharField(choices=[('draft', 'Draft / Upcoming'), ('active', 'Active (Live)'), ('paused', 'Paused'), ('ended', 'Ended'), ('winners_declared', 'Winners Declared')], default='draft', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Master on/off switch. If False, campaign is completely hidden everywhere.')),
                ('show_on_homepage', models.BooleanField(default=True, help_text='Display promotional strip/card on Homepage when live')),
                ('show_on_register_page', models.BooleanField(default=True, help_text='Display contest highlight on Sign-up page when live')),
                ('winner_announcement_date', models.DateTimeField(blank=True, help_text='Optional date when winners will be announced', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaign / Lucky Draw',
                'verbose_name_plural': 'Campaigns & Lucky Draws',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CampaignParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('ticket_number', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('is_eligible', models.BooleanField(default=True, help_text='Whether this user is eligible for lucky draw')),
                ('is_winner', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='common.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Participant',
                'verbose_name_plural': 'Campaign Participants',
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'ticket_number'), ('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CampaignPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('rank', models.PositiveSmallIntegerField(default=1, help_text='1 for 1st Prize, 2 for 2nd Prize, 3 for 3rd Prize, etc.')),
                ('title', models.CharField(help_text='e.g. 1st Prize: 43-inch Smart 4K TV', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Brand New Smart TV with 1-Year Warranty', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/prizes/')),
                ('approx_value', models.DecimalField(blank=True, decimal_places=2, help_text='Approx value in INR', max_digits=10, null=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='common.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaign Prize',
                'verbose_name_plural': 'Campaign Prizes',
                'ordering': ['rank', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='CampaignWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('ticket_number', models.CharField(blank=True, default='', max_length=50)),
                ('is_published', models.BooleanField(default=True, help_text='Display publicly on the website')),
                ('notes', models.TextField(blank=True, help_text='Admin notes, verification remarks, dispatch status, etc.')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='common.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_record', to='common.campaignparticipant')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='common.campaignprize')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Winner',
                'verbose_name_plural': 'Campaign Winners',
                'ordering': ['prize__rank', '-created_at'],
                'unique_together': {('campaign', 'prize'), ('campaign', 'user')},
            },
        ),
    ]
