# Generated by Django 6.0.4 on 2026-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('delivery_partner', 'Delivery Partner'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
