# Generated by Django 6.0.4 on 2026-05-03 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('items', '0006_product_gender_alter_sellerprofile_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerShopAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('shop_name', models.CharField(help_text='Registered shop name', max_length=150)),
                ('shop_phone', models.CharField(max_length=15)),
                ('shop_email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('pickup_instructions', models.TextField(blank=True, help_text='Instructions for delivery pickup')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_address', to='items.sellerprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name_plural': 'Seller Shop Addresses',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='Recipient name', max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('address_type', models.CharField(choices=[('shipping', '📦 Shipping Address'), ('billing', '💳 Billing Address'), ('both', '🔄 Both Shipping & Billing')], default='shipping', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default for checkout')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='accounts_ad_user_id_c8244c_idx'), models.Index(fields=['user', 'is_active'], name='accounts_ad_user_id_80f6dc_idx')],
            },
        ),
    ]
