# Generated by Django 6.0.4 on 2026-06-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='phone',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
