# Generated by Django 6.0.4 on 2026-06-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_otprequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('delivery_partner', 'Delivery Partner'), ('admin', 'Admin'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
    ]
