# Generated by Django 6.0.4 on 2026-05-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='commision_percentage',
            field=models.FloatField(default=0),
        ),
    ]
