# Generated by Django 6.0.4 on 2026-05-03 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_category_commision_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', '👨 Men'), ('women', '👩 Women'), ('boys', '👦 Boys'), ('girls', '👧 Girls'), ('unisex', '👫 Unisex'), ('kids', '🧒 Kids (2-12)'), ('teen', '🧑 Teen (13-19)')], help_text='Target audience (optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gender', 'status'], name='items_produ_gender_1ee005_idx'),
        ),
    ]
