# Generated by Django 6.0.4 on 2026-05-09 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_category_is_deleted_product_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('size_value', models.CharField(help_text="e.g., 'M', '6', '24x36 inches', '18k'", max_length=50)),
                ('size_type', models.CharField(choices=[('standard', 'Standard / Free Size'), ('clothing', 'Clothing (XS-XXL, Numeric)'), ('jewelry', 'Jewelry (Ring Size, Chain Length, Carat)'), ('furniture', 'Furniture (Dimensions, Configuration)'), ('footwear', 'Footwear (US/UK/EU)'), ('custom', 'Custom / Other')], default='standard', max_length=20)),
                ('color', models.CharField(blank=True, help_text='Optional color/finish', max_length=50)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides base product price', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text="Custom specs: {'material': 'Gold', 'fit': 'Slim', 'assembly': 'Required'}")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='items.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['size_value'],
                'constraints': [models.UniqueConstraint(fields=('product', 'size_value', 'color'), name='unique_variant_per_product')],
            },
        ),
    ]
