# Generated by Django 6.0.4 on 2026-05-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', '👨 Men'), ('women', '👩 Women'), ('unisex', '👫 Unisex'), ('kids', '🧒 Kids (2-12)'), ('teen', '🧑 Teen (13-19)')], help_text='Target audience (optional)', max_length=20, null=True),
        ),
    ]
