# Generated by Django 6.0.4 on 2026-06-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_populate_new_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
