# Generated by Django 6.0.4 on 2026-06-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_sellerprofile_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='razorpay_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='razorpay_fund_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
