# Generated by Django 6.0.4 on 2026-06-06 06:17

import django.core.validators
import django.db.models.deletion
import items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_sellerprofile_razorpay_contact_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='video',
            field=models.FileField(blank=True, help_text='Optional: Upload video of the product', null=True, upload_to='reviews/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm']), items.models.validate_video_size]),
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Optional review title', max_length=200)),
                ('review', models.TextField(help_text='Your detailed review', max_length=2000)),
                ('images', models.ImageField(blank=True, help_text='Optional: Upload photos of the packaging/delivery', null=True, upload_to='reviews/sellers/')),
                ('video', models.FileField(blank=True, help_text='Optional: Upload video of the packaging/delivery', null=True, upload_to='reviews/sellers/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm']), items.models.validate_video_size])),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Auto-set if user bought from this seller')),
                ('is_approved', models.BooleanField(default=True, help_text='Set to False for moderation queue')),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='items.sellerprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Review',
                'verbose_name_plural': 'Seller Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', '-rating'], name='items_selle_seller__cbb494_idx'), models.Index(fields=['seller', '-created_at'], name='items_selle_seller__f01ebd_idx'), models.Index(fields=['is_approved', '-created_at'], name='items_selle_is_appr_61cd17_idx')],
                'unique_together': {('seller', 'user')},
            },
        ),
    ]
