# Generated by Django 6.0.4 on 2026-06-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, default='India', help_text='e.g. India, USA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='e.g. Cotton, Leather, Wood', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, help_text='e.g. 1 Year Manufacturer Warranty', max_length=100, null=True),
        ),
    ]
