# Generated by Django 6.0.4 on 2026-06-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_product_country_of_origin_product_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='pan_card_file',
            field=models.FileField(blank=True, null=True, upload_to='seller_pan_cards/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
