# Generated by Django 6.0.4 on 2026-06-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_sellerprofile_pan_card_file_sellerprofile_pan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Category icon image (displayed on storefront/menus)', null=True, upload_to='category_icons/'),
        ),
    ]
