# Generated by Django 6.0.4 on 2026-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=True, help_text='Designates whether the product is eligible for return/refund'),
        ),
    ]
