# Generated by Django 6.0.4 on 2026-05-31 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cartitem_unique_together_cartitem_variant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('title', models.CharField(help_text='For internal tracking/admin use or overlay title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or description text', max_length=300, null=True)),
                ('image', models.ImageField(help_text='Upload premium high-resolution banner image', upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile-optimized image (falls back to main image if blank)', null=True, upload_to='banners/mobile/')),
                ('link_url', models.CharField(blank=True, default='#', help_text='URL redirect link (e.g. /items/?category=sarees)', max_length=500)),
                ('banner_type', models.CharField(choices=[('main_slider', '✨ Top Main Slider/Hero Banner'), ('festive_sale', '🎉 Festive Sale Banner'), ('coming_soon', '⏰ Coming Soon Banner')], default='main_slider', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Only show active banners on home page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display priority (lower numbers shown first)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Homepage Banner',
                'verbose_name_plural': 'Homepage Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
