# Generated by Django 6.0.4 on 2026-06-01 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_homepagebanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchSaleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('title', models.CharField(default='Newly Launched Sale is LIVE!', help_text='Banner headline (e.g. Newly Launched Sale is LIVE!)', max_length=200)),
                ('subtitle', models.TextField(default='StallCart is officially live! Celebrate our grand launch with premium fashion at unbeatable prices. Minimum 40% to 80% OFF across the store!', help_text='Long description text')),
                ('coupon_code', models.CharField(blank=True, default='LAUNCH100', help_text='Coupon code to highlight (optional, leave blank to hide)', max_length=50, null=True)),
                ('btn_text', models.CharField(default='Shop the Sale', help_text='Text shown on CTA button', max_length=100)),
                ('link_url', models.CharField(default='/items/', help_text='Redirect link for the CTA button', max_length=500)),
                ('end_datetime', models.DateTimeField(help_text='The date and time when the sale/countdown ends (timezone-aware)')),
                ('is_active', models.BooleanField(default=True, help_text='Check to display this banner on the home page')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Launch Sale Banner',
                'verbose_name_plural': 'Launch Sale Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
