# Generated by Django 6.0.4 on 2026-08-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_populate_homepage_sliders'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementbanner',
            name='badge_text',
            field=models.CharField(default='LIVE NOW', help_text='Small badge text above title (e.g. 🇮🇳 FREEDOM SALE LIVE)', max_length=100),
        ),
    ]
