# Generated by Django 6.0.4 on 2026-05-02 08:11

import django.core.validators
import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0005_category_commision_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('unique_order_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('shipping_address', models.JSONField(default=dict)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'Razorpay (UPI/Card/NetBanking)'), ('wallet', 'Wallet')], default='cod', max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', '🟡 Order Placed'), ('confirmed', '🔵 Order Confirmed'), ('processing', '🟠 Processing'), ('shipped', '🟣 Shipped'), ('out_for_delivery', '🔵 Out for Delivery'), ('delivered', '🟢 Delivered'), ('cancelled', '🔴 Cancelled'), ('returned', '🔄 Returned'), ('refund_initiated', '💰 Refund Initiated')], default='pending', max_length=30)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('changed_mind', 'Changed my mind'), ('found_cheaper', 'Found cheaper elsewhere'), ('delivery_delay', 'Delivery delay'), ('wrong_address', 'Wrong address'), ('other', 'Other')], max_length=50, null=True)),
                ('cancellation_remarks', models.TextField(blank=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.CharField(blank=True, choices=[('damaged', 'Damaged/Defective'), ('wrong_item', 'Wrong item sent'), ('not_as_described', 'Not as described'), ('size_issue', 'Size/Color issue'), ('late_delivery', 'Late delivery'), ('other', 'Other')], max_length=50, null=True)),
                ('return_remarks', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_returned', models.BooleanField(default=False)),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.sellerprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('image', models.ImageField(help_text='Upload clear photos showing damage/defect (Max 5MB)', upload_to='returns/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), orders.models.validate_image_size])),
                ('caption', models.CharField(blank=True, help_text="Brief description of the issue shown (e.g., 'Torn seam on left sleeve')", max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as main evidence image for this return')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Return Evidence Image',
                'verbose_name_plural': 'Return Evidence Images',
                'ordering': ['-created_at', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(choices=[('pending', '🟡 Order Placed'), ('confirmed', '🔵 Order Confirmed'), ('processing', '🟠 Processing'), ('shipped', '🟣 Shipped'), ('out_for_delivery', '🔵 Out for Delivery'), ('delivered', '🟢 Delivered'), ('cancelled', '🔴 Cancelled'), ('returned', '🔄 Returned'), ('refund_initiated', '💰 Refund Initiated')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged/Defective'), ('wrong_item', 'Wrong item sent'), ('not_as_described', 'Not as described'), ('size_issue', 'Size/Color issue'), ('late_delivery', 'Late delivery'), ('other', 'Other')], max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', '🟡 Return Requested'), ('approved', '🔵 Approved'), ('pickup_scheduled', '🟠 Pickup Scheduled'), ('picked_up', '🟣 Picked Up'), ('received', '🟢 Received at Warehouse'), ('refund_initiated', '💰 Refund Initiated'), ('completed', '✅ Completed'), ('rejected', '❌ Rejected')], default='requested', max_length=30)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_address', models.JSONField(default=dict)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_method', models.CharField(blank=True, choices=[('original', 'Original Payment Method'), ('wallet', 'StallCart Wallet'), ('bank', 'Bank Transfer')], max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('images', models.ManyToManyField(blank=True, to='orders.orderreturnimage')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.orderitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderreturnimage',
            name='return_request',
            field=models.ForeignKey(help_text='The return request this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='return_images', to='orders.returnrequest'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturnimage',
            index=models.Index(fields=['return_request', '-created_at'], name='orders_orde_return__478c6e_idx'),
        ),
    ]
