# Generated by Django 6.0.4 on 2026-05-30 11:57

import django.core.validators
import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_deleted_orderitem_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderreturnimage',
            name='orders_orde_return__478c6e_idx',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='images',
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='actioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Order Placed'), ('confirmed', '🔵 Order Confirmed'), ('processing', '🟠 Processing'), ('shipped', '🟣 Shipped'), ('out_for_delivery', '🔵 Out for Delivery'), ('delivered', '🟢 Delivered'), ('cancelled', '🔴 Cancelled'), ('returned', '🔄 Returned'), ('refund_initiated', '💰 Refund Initiated'), ('refunded', '✅ Refunded')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderreturnimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderreturnimage',
            name='image',
            field=models.ImageField(upload_to='returns/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), orders.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='orderreturnimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderreturnimage',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_images', to='orders.returnrequest'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='new_status',
            field=models.CharField(choices=[('pending', '🟡 Order Placed'), ('confirmed', '🔵 Order Confirmed'), ('processing', '🟠 Processing'), ('shipped', '🟣 Shipped'), ('out_for_delivery', '🔵 Out for Delivery'), ('delivered', '🟢 Delivered'), ('cancelled', '🔴 Cancelled'), ('returned', '🔄 Returned'), ('refund_initiated', '💰 Refund Initiated'), ('refunded', '✅ Refunded')], max_length=30),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('requested', '🟡 Return Requested'), ('approved', '🔵 Approved'), ('rejected', '❌ Rejected'), ('pickup_scheduled', '🟠 Pickup Scheduled'), ('picked_up', '🟣 Picked Up'), ('received', '🟢 Received at Warehouse'), ('refund_initiated', '💰 Refund Initiated'), ('completed', '✅ Completed')], default='requested', max_length=30),
        ),
    ]
