# Generated by Django 6.0.4 on 2026-05-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_productreview'),
        ('orders', '0003_remove_orderreturnimage_orders_orde_return__478c6e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='items.productvariant'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='razorpay_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_instructions',
            field=models.TextField(blank=True, help_text='For manual COD refunds'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('manual_pending', 'Manual Transfer Pending')], default='pending', max_length=20),
        ),
    ]
