# Generated by Django 6.0.4 on 2026-05-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_variant_returnrequest_razorpay_refund_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Order Placed'), ('confirmed', '🔵 Order Confirmed'), ('processing', '🟠 Processing'), ('shipped', '🟣 Shipped'), ('out_for_delivery', '🔵 Out for Delivery'), ('delivered', '🟢 Delivered'), ('cancelled', '🔴 Cancelled'), ('returned', '🔄 Returned'), ('returned_to_source', '🔄 Returned to Source (RTO)'), ('refund_initiated', '💰 Refund Initiated'), ('refunded', '✅ Refunded')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='new_status',
            field=models.CharField(choices=[('pending', '🟡 Order Placed'), ('confirmed', '🔵 Order Confirmed'), ('processing', '🟠 Processing'), ('shipped', '🟣 Shipped'), ('out_for_delivery', '🔵 Out for Delivery'), ('delivered', '🟢 Delivered'), ('cancelled', '🔴 Cancelled'), ('returned', '🔄 Returned'), ('returned_to_source', '🔄 Returned to Source (RTO)'), ('refund_initiated', '💰 Refund Initiated'), ('refunded', '✅ Refunded')], max_length=30),
        ),
    ]
