# Generated by Django 6.0.4 on 2026-06-03 19:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_sellerprofile_account_holder_name_and_more'),
        ('orders', '0005_alter_order_status_alter_orderstatuslog_new_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('settlement_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net amount paid to seller', max_digits=10)),
                ('commission_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform commission deducted', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction reference ID', max_length=100, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('order_items', models.ManyToManyField(blank=True, related_name='settlements', to='orders.orderitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='items.sellerprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Seller Settlement',
                'verbose_name_plural': 'Seller Settlements',
                'ordering': ['-created_at'],
            },
        ),
    ]
