# Generated by Django 6.0.4 on 2026-06-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_sellersettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettlement',
            name='razorpay_payout_id',
            field=models.CharField(blank=True, help_text='RazorpayX Payout ID', max_length=100, null=True, unique=True),
        ),
    ]
