# Generated by Django 6.0.4 on 2026-06-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_sellersettlement_razorpay_payout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_payment_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_placed_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_refund_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_payment_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_placed_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_refund_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='customer_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='seller_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
