# Generated by Django 6.0.4 on 2026-06-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_customer_payment_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Order Placed'), ('confirmed', '🔵 Order Confirmed'), ('processing', '🟠 Processing'), ('shipped', '🟣 Shipped'), ('out_for_delivery', '🔵 Out for Delivery'), ('delivered', '🟢 Delivered'), ('cancelled', '🔴 Cancelled'), ('returned', '🔄 Returned'), ('returned_to_source', '🔄 Returned to Source (RTO)'), ('refund_initiated', '💰 Refund Initiated'), ('refunded', '✅ Refunded')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
