# Generated by Django 6.0.4 on 2026-06-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_shipment_id_order_shiprocket_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiprocket_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Order Placed'), ('confirmed', '🔵 Order Confirmed'), ('processing', '🟠 Processing'), ('shipped', '🟣 Shipped'), ('out_for_delivery', '🔵 Out for Delivery'), ('delivered', '🟢 Delivered'), ('cancelled', '🔴 Cancelled'), ('returned', '🔄 Returned'), ('returned_to_source', '🔄 Returned to Source (RTO)'), ('refund_initiated', '💰 Refund Initiated'), ('refunded', '✅ Refunded'), ('courier_failed_pickup', '🔴 Pickup Failed (Courier)'), ('seller_unresponsive', '🔴 Seller Unresponsive / Cancelled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Order Placed'), ('confirmed', '🔵 Order Confirmed'), ('processing', '🟠 Processing'), ('shipped', '🟣 Shipped'), ('out_for_delivery', '🔵 Out for Delivery'), ('delivered', '🟢 Delivered'), ('cancelled', '🔴 Cancelled'), ('returned', '🔄 Returned'), ('returned_to_source', '🔄 Returned to Source (RTO)'), ('refund_initiated', '💰 Refund Initiated'), ('refunded', '✅ Refunded'), ('courier_failed_pickup', '🔴 Pickup Failed (Courier)'), ('seller_unresponsive', '🔴 Seller Unresponsive / Cancelled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='new_status',
            field=models.CharField(choices=[('pending', '🟡 Order Placed'), ('confirmed', '🔵 Order Confirmed'), ('processing', '🟠 Processing'), ('shipped', '🟣 Shipped'), ('out_for_delivery', '🔵 Out for Delivery'), ('delivered', '🟢 Delivered'), ('cancelled', '🔴 Cancelled'), ('returned', '🔄 Returned'), ('returned_to_source', '🔄 Returned to Source (RTO)'), ('refund_initiated', '💰 Refund Initiated'), ('refunded', '✅ Refunded'), ('courier_failed_pickup', '🔴 Pickup Failed (Courier)'), ('seller_unresponsive', '🔴 Seller Unresponsive / Cancelled')], max_length=30),
        ),
    ]
