# Generated by Django 6.0.4 on 2026-06-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_shiprocket_status_orderitem_shiprocket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettlement',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='True if settlement notification email has been sent to the seller'),
        ),
    ]
