# Generated by Django 6.0.4 on 2026-06-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_systemactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
